"""empty message

Revision ID: 2ccce1802208
Revises: aea0bf64e3d4
Create Date: 2023-06-19 22:06:30.042229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ccce1802208'
down_revision = 'aea0bf64e3d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('perfil', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url_profile_pic', sa.String(length=128), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('perfil', schema=None) as batch_op:
        batch_op.drop_column('url_profile_pic')

    # ### end Alembic commands ###
