"""empty message

Revision ID: 2d32f3a4bdc8
Revises: 9802204cf490
Create Date: 2023-06-08 19:48:17.413485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d32f3a4bdc8'
down_revision = '9802204cf490'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('talent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('practice_time', sa.String(length=20), nullable=False),
    sa.Column('about_you', sa.String(length=100), nullable=False),
    sa.Column('categories_talent', sa.String(length=100), nullable=False),
    sa.Column('range_talent', sa.String(length=100), nullable=False),
    sa.Column('perfil_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['perfil_id'], ['perfil.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('talent')
    # ### end Alembic commands ###
