"""empty message

Revision ID: 6166a0d5d014
Revises: c0b077e0cce1
Create Date: 2023-06-14 23:05:05.155167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6166a0d5d014'
down_revision = 'c0b077e0cce1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_constraint('categories_talent_id_fkey', type_='foreignkey')
        batch_op.drop_column('talent_id')

    with op.batch_alter_table('talent_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('perfil_solicitante_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('talent_request_perfil_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'perfil', ['perfil_solicitante_id'], ['id'])
        batch_op.drop_column('perfil_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('talent_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('perfil_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('talent_request_perfil_id_fkey', 'perfil', ['perfil_id'], ['id'])
        batch_op.drop_column('perfil_solicitante_id')

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('talent_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('categories_talent_id_fkey', 'talent', ['talent_id'], ['id'])

    # ### end Alembic commands ###
