"""empty message

Revision ID: 89d396af6b7e
Revises: 2d32f3a4bdc8
Create Date: 2023-06-08 20:03:06.911274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89d396af6b7e'
down_revision = '2d32f3a4bdc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('categorie_name', sa.String(length=100), nullable=False),
    sa.Column('talent_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['talent_id'], ['talent.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('talent', schema=None) as batch_op:
        batch_op.add_column(sa.Column('talent_name', sa.String(length=100), nullable=False))
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('talent', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.drop_column('talent_name')

    op.drop_table('categories')
    # ### end Alembic commands ###
