"""empty message

Revision ID: a52f3074d282
Revises: 2ccce1802208
Create Date: 2023-06-20 00:56:37.916602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a52f3074d282'
down_revision = '2ccce1802208'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('perfil', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=400), nullable=False))

    with op.batch_alter_table('talent', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imagetalent_url', sa.String(length=400), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('talent', schema=None) as batch_op:
        batch_op.drop_column('imagetalent_url')

    with op.batch_alter_table('perfil', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
