"""empty message

Revision ID: aea0bf64e3d4
Revises: 6166a0d5d014
Create Date: 2023-06-16 16:33:02.659433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aea0bf64e3d4'
down_revision = '6166a0d5d014'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('talent_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('perfil_receptor_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'perfil', ['perfil_receptor_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('talent_request', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('perfil_receptor_id')

    # ### end Alembic commands ###
